<?php
    require_once("controllers/helpers.php");
    require_once("controllers/headerController.php");
    require_once("controllers/registerController.php");
    require_once("controllers/mailController.php");
    require_once("controllers/loginController.php");
    require_once("controllers/portafolioController.php");
    require_once("controllers/contactoController.php")
?>